/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/back-top/BackTop.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    EmptyData: typeof import('./src/components/empty-data/EmptyData.vue')['default']
    FeatureArea: typeof import('./src/components/header/components/pc/FeatureArea.vue')['default']
    FooterCpt: typeof import('./src/components/footer/FooterCpt.vue')['default']
    HeaderView: typeof import('./src/components/header/HeaderView.vue')['default']
    IEpClock: typeof import('~icons/ep/clock')['default']
    IEpLollipop: typeof import('~icons/ep/lollipop')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    MenuArea: typeof import('./src/components/header/components/pc/MenuArea.vue')['default']
    NoteList: typeof import('./src/components/note-list/NoteList.vue')['default']
    NoteListItem: typeof import('./src/components/note-list/NoteListItem.vue')['default']
    OpenSideBarM: typeof import('./src/components/header/components/mobile/OpenSideBarM.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCpt: typeof import('./src/components/search/SearchCpt.vue')['default']
    SideBarViewM: typeof import('./src/components/header/components/mobile/SideBarViewM.vue')['default']
    ThemeSwc: typeof import('./src/components/header/components/pc/ThemeSwc.vue')['default']
    TitleArea: typeof import('./src/components/header/components/pc/TitleArea.vue')['default']
  }
}
